### ISSUE TITLE
PDF generation

### ISSUE THREAD

**Issue by mattadamson** [Swagger2Markup/swagger2markup#145]
Is anyone using PDF generation successfully?

From the current example project https://github.com/Swagger2Markup/swagger2markup-maven-project-template/blob/master/pom.xml, I noticed the section 

```
                    <execution>
                        <id>output-pdf</id>
                        <phase>generate-resources</phase>
                        <goals>
                            <goal>process-asciidoc</goal>
                        </goals>
                        <configuration>
                            <backend>pdf</backend>
                            <outputDirectory>${asciidoctor.pdf.output.directory}</outputDirectory>
                        </configuration>
                    </execution>
```

is commented out. This dependency is also referenced

```
                   <dependency>
                        <groupId>org.asciidoctor</groupId>
                        <artifactId>asciidoctorj-pdf</artifactId>
                        <version>1.5.0-alpha.10.1</version>
                    </dependency>
```

I just tried to generate a PDF and received an exception which isn't clear on the root cause

```
Caused by: org.apache.maven.plugin.PluginExecutionException: Execution output-pdf of goal org.asciidoctor:asciidoctor-maven-plugin:1.5.3:process-asciidoc failed: (Errno::ENOENT) C:/Users/madamson/.m2/repository/org/asciidoctor/asciidoctorj-pdf/1.5.0-alpha.10.1/asciidoctorj-pdf-1.5.0-alpha.10.1.jar!D:/gems/addressable-2.3.8/data/unicode.data
                at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:115)
                at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
                ... 19 more

Caused by: org.jruby.exceptions.RaiseException: (Errno::ENOENT) C:/Users/madamson/.m2/repository/org/asciidoctor/asciidoctorj-pdf/1.5.0-alpha.10.1/asciidoctorj-pdf-1.5.0-alpha.10.1.jar!D:/gems/addressable-2.3.8/data/unicode.data
                at org.jruby.RubyFile.initialize(org/jruby/RubyFile.java:370)
                at org.jruby.RubyIO.open(org/jruby/RubyIO.java:1179)
                at RUBY.IDNA(C:/Users/madamson/.m2/repository/org/asciidoctor/asciidoctorj-pdf/1.5.0-alpha.10.1/asciidoctorj-pdf-1.5.0-alpha.10.1.jar!/gems/addressable-2.3.8/lib/addressable/idna/pure.rb:331)
                at RUBY.Addressable(C:/Users/madamson/.m2/repository/org/asciidoctor/asciidoctorj-pdf/1.5.0-alpha.10.1/asciidoctorj-pdf-1.5.0-alpha.10.1.jar!/gems/addressable-2.3.8/lib/addressable/idna/pure.rb:20)
                at RUBY.(root)(C:/Users/madamson/.m2/repository/org/asciidoctor/asciidoctorj-pdf/1.5.0-alpha.10.1/asciidoctorj-pdf-1.5.0-alpha.10.1.jar!/gems/addressable-2.3.8/lib/addressable/idna/pure.rb:19)
                at org.jruby.RubyKernel.require(org/jruby/RubyKernel.java:1040)
                at RUBY.(root)(/C:/Users/madamson/.m2/repository/org/jruby/jruby-complete/1.7.23/jruby-complete-1.7.23.jar!/META-INF/jruby.home/lib/ruby/shared/rubygems/core_ext/kernel_require.rb:1)
```

**Comment by jfiala** [comment]
you have to add the jruby/asciidoctorj dependencies to the plugin dependencies and then it works :).

for more information see
https://github.com/asciidoctor/asciidoctor-maven-examples/tree/master/asciidoctor-pdf-example

**Comment by jfiala** [comment]
this should be fixed with this PR:
https://github.com/Swagger2Markup/swagger2markup-maven-project-template/pull/1

**Comment by jfiala** [comment]
@Kabhal do you need something more to accept the PR Swagger2Markup/swagger2markup-maven-project-template#1?

**Comment by hantsy** [comment]
@Kabhal I got the same error, but add JRuby 1.7.21 as dependencies explicitly. It disappeared.

               <dependency>
                        <groupId>org.jruby</groupId>
                        <artifactId>jruby-complete</artifactId>
                        <version>${jruby.version}</version>
                    </dependency>
