### ISSUE TITLE
Instagram example schema fails to convert w/ Swagger2Markup 1.0.0

### ISSUE THREAD

**Issue by starlightknight** [Swagger2Markup/swagger2markup#150]
Swagger2Markup version: 1.0.0

Problem description: 
Swagger2Markup 1.0.0 fails to convert the instagram.yaml example from Swagger Editor. This is a regression from 0.9.2, where the file works fine. You can grab the yaml schema from editor.swagger.io, open example -> instagram.yaml

I use Swagger2Markup downstream as part of my Swagger Confluence project, and this issue came to my attention via one of my users. This is how I invoke Swagger2Markup:

https://github.com/starlightknight/swagger-confluence/blob/develop/swagger-confluence-core/src/main/java/net/slkdev/swagger/confluence/service/impl/SwaggerToAsciiDocServiceImpl.java

On my previous version that used Swagger2Markup 0.9.2, this file works successfully:

https://github.com/starlightknight/swagger-confluence/blob/2.1-RELEASE/swagger-confluence-core/src/main/java/net/slkdev/swagger/confluence/service/impl/SwaggerToAsciiDocServiceImpl.java

The resulting error is:
```
2016-05-24 18:43:26.350  INFO - [main] n.s.s.c.s.i.SwaggerToAsciiDocServiceImpl : Converting Swagger Schema to Ascii Doc...
2016-05-24 18:43:26.679  WARN - [main] i.s.u.PropertyDeserializer               : no property from null, null, {ENUM=null, TITLE=null, DESCRIPTION=null, DEFAULT=null, PATTERN=null, DESCRIMINATOR=null, MIN_ITEMS=null, MAX_ITEMS=null, MIN_PROPERTIES=null, MAX_PROPERTIES=null, MIN_LENGTH=null, MAX_LENGTH=null, MINIMUM=null, MAXIMUM=null, EXCLUSIVE_MINIMUM=null, EXCLUSIVE_MAXIMUM=null, UNIQUE_ITEMS=null, EXAMPLE=null, TYPE=null, FORMAT=null, READ_ONLY=null, VENDOR_EXTENSIONS={}}
2016-05-24 18:43:27.022  INFO - [main] i.g.s.i.d.b.PathsDocumentBuilder         : Operation processed : '/geographies/{geo-id}/media/recent get' (normalized id = 'geographies_geo-id_media_recent_get')
2016-05-24 18:43:27.050  INFO - [main] i.g.s.i.d.b.PathsDocumentBuilder         : Operation processed : '/locations/search get' (normalized id = 'locations_search_get')
2016-05-24 18:43:27.063  INFO - [main] i.g.s.i.d.b.PathsDocumentBuilder         : Operation processed : '/locations/{location-id} get' (normalized id = 'locations_location-id_get')
2016-05-24 18:43:27.090  INFO - [main] i.g.s.i.d.b.PathsDocumentBuilder         : Operation processed : '/locations/{location-id}/media/recent get' (normalized id = 'locations_location-id_media_recent_get')
2016-05-24 18:43:27.098  INFO - [main] i.g.s.i.d.b.PathsDocumentBuilder         : Operation processed : '/media/popular get' (normalized id = 'media_popular_get')
Exception in thread "main" java.lang.NullPointerException: property must not be null
    at org.apache.commons.lang3.Validate.notNull(Validate.java:222)
    at io.github.swagger2markup.internal.utils.PropertyUtils.getType(PropertyUtils.java:43)
    at io.github.swagger2markup.internal.utils.PropertyUtils.getType(PropertyUtils.java:54)
    at io.github.swagger2markup.internal.document.builder.MarkupDocumentBuilder.buildPropertiesTable(MarkupDocumentBuilder.java:182)
    at io.github.swagger2markup.internal.document.builder.PathsDocumentBuilder.inlineDefinitions(PathsDocumentBuilder.java:744)
    at io.github.swagger2markup.internal.document.builder.PathsDocumentBuilder.buildOperation(PathsDocumentBuilder.java:277)
    at io.github.swagger2markup.internal.document.builder.PathsDocumentBuilder.buildOperation(PathsDocumentBuilder.java:254)
    at io.github.swagger2markup.internal.document.builder.PathsDocumentBuilder.buildsPathsSection(PathsDocumentBuilder.java:152)
    at io.github.swagger2markup.internal.document.builder.PathsDocumentBuilder.build(PathsDocumentBuilder.java:140)
    at io.github.swagger2markup.Swagger2MarkupConverter.toString(Swagger2MarkupConverter.java:234)
```

**Comment by RobWin** [comment]
Hi,
thx for using Swagger2Markup. If you like it, we would love to get your GitHub Star.

I have a look at the issue.

**Comment by Kabhal** [comment]
Extracted problem in instagram.yaml :
```
    responses:
        200:
          description: OK
          schema:
            type: object
            description: List of all media with added `distance` property
            properties:
              data:
                type: array
                items:
                  allOf:
                    - $ref: '#/definitions/Media'
                    -
                      properties:
                        distance:
                          type: number
```

**Comment by RobWin** [comment]
Unfortunately I'm on vacation for the next three weeks.

**Comment by Kabhal** [comment]
Happy hollidays :)

By the way: Swagger editor does not fail on Instagram.yaml but shows nothing ('undefined') :
![allofarray](https://cloud.githubusercontent.com/assets/6772693/15567393/6f7843a8-2326-11e6-8220-169bf13f4dce.png)

Anyway I'll protected code against NPE.

**Comment by Kabhal** [comment]
An empty, anonymous, object is created in place of composed model as a workaround (similar to current Swagger UI behavior with 'undefined')

**Comment by starlightknight** [comment]
Well at least this fix makes us consistent across the tools, though it looks like we unraveled an upstream bug here. Did you guys already open an issue upstream about this, or should we do that and attach the information you found here?

**Comment by Kabhal** [comment]
I don't think we opened an issue, you can check and open an issue at Swagger-core/parser and link it here for informative purpose.
