### ISSUE TITLE
Support for HTML/markdown from Description

### ISSUE THREAD

**Issue by Gautham** [Swagger2Markup/swagger2markup#196]
Swagger2Markup version:swagger2markup-cli-1.1.0

Problem description:
When I use html to markup descriptions in Swagger doc, it works correctly in UI but the conversion fails.

```
<ul><li>A : some A</li><li>B</li></ol>
```

This succeeds but shows as-is in the generated doc. (Note the incorrect OL tag)

```
<ul><li>A : some A</li><li>B</li></ul>
```

This fails with the following stacktrace :

```
Exception in thread "main" java.lang.IllegalArgumentException: text must not be blank
    at org.apache.commons.lang3.Validate.notBlank(Validate.java:451)
    at io.github.swagger2markup.markup.builder.internal.asciidoc.AsciiDocBuilder.paragraph(AsciiDocBuilder.java:91)
    at io.github.swagger2markup.markup.builder.internal.AbstractMarkupDocBuilder.paragraph(AbstractMarkupDocBuilder.java:215)
    at io.github.swagger2markup.internal.document.builder.MarkupDocumentBuilder.buildDescriptionParagraph(MarkupDocumentBuilder.java:360)
    at io.github.swagger2markup.internal.document.builder.DefinitionsDocumentBuilder.modelDescription(DefinitionsDocumentBuilder.java:282)
    at io.github.swagger2markup.internal.document.builder.DefinitionsDocumentBuilder.buildDescriptionParagraph(DefinitionsDocumentBuilder.java:276)
    at io.github.swagger2markup.internal.document.builder.DefinitionsDocumentBuilder.buildDefinition(DefinitionsDocumentBuilder.java:196)
    at io.github.swagger2markup.internal.document.builder.DefinitionsDocumentBuilder.buildDefinition(DefinitionsDocumentBuilder.java:171)
    at io.github.swagger2markup.internal.document.builder.DefinitionsDocumentBuilder.buildDefinitionsSection(DefinitionsDocumentBuilder.java:110)
    at io.github.swagger2markup.internal.document.builder.DefinitionsDocumentBuilder.build(DefinitionsDocumentBuilder.java:97)
    at io.github.swagger2markup.Swagger2MarkupConverter.toFile(Swagger2MarkupConverter.java:207)
    at io.github.swagger2markup.cli.Application.run(Application.java:84)
    at io.github.swagger2markup.cli.Application.main(Application.java:61)
```

I want to define lists.etc which can be rendered in both Swagger UI and be apparent in the generated doc (without manual editing). Any help with this will be greatly appreciated!

**Comment by RobWin** [comment]
Hi,

could you please provide a full Swagger File so that we can reproduce the issue?

Btw: If you like and use Swagger2Markup,we would love to get your GitHub stars.

**Comment by RobWin** [comment]
Hi,

HTML is not supported, but you can use Markdown, for example:

```
      description: |
        Multiple status values can be provided with comma seperated strings
        This a list
          * item1
          * item2

          - item1
          - item2
            - subitem 1
```

**Comment by RobWin** [comment]
Does that solve your issue?

**Comment by Gautham** [comment]
Hi Rob,

sorry for the late reply. For some reason, I couldn't get markdown rendered and got stuck with that. When I got some time to look into it again, I realized that it was an issue with the editor. It works correctly with Swagger UI and the generated pdf!

Thanks for the support :)

**Comment by RobWin** [comment]
you are welcome

**Comment by monism** [comment]
I am getting same issue the above text must not be blank

I am passing a json file, any hellp will be aprreciated

**Comment by thomasbuengener** [comment]
The problem ist with nested tables. your example descrition above with the html tables will be transformed to the following if the description ends up beeing inside a table already.

```
\|===
\|Header Column

\|Content column
\|===
```

In nested tables "|" must be replaced by "!" instead of beeing escaped as "\|".

See http://mrhaki.blogspot.com/2017/04/awesome-asciidoctor-nested-tables.html

The follwoing will work inside nested tables as it is not escape by swagger2markup, but will not work in swagger-ui as it is asciidoc not markdown.

```
!===
!head1!head2!
!a!b!
!===

```
Test case:
```
swagger: "2.0"
info:
  title: Simple API overview
  version: v2
tags:
- name: Tag1
  description: great tag
paths:
  /:
    get:
      tags:
      - Tag1
      operationId: listVersionsv2
      summary: List API versions
      produces:
      - application/json
      responses:
        "200":
          description: |
            Multiple status values can be provided with comma seperated strings
            This a list
    
              * item1
              * item2
    
              - item1
              - item2
                - subitem 1
    
            This is a table
    
            <table>
              <tr><th>Header Column</th></tr>
              <tr><td>Content column</td></tr>
            </table>
            
            more tables
            
            |aa|bb|
            |--|--|
            |11|22|
            
            

```
