### ISSUE TITLE
NullPointerException if using $ref in array items

### ISSUE THREAD

**Issue by reacherhsu** [Swagger2Markup/swagger2markup#213]
**Swagger2Markup version:** 
1.1.1-SNAPSHOT

**Problem description:**
After setting true to below property in config file:
swagger2markup.generatedExamplesEnabled=true

then got the NullPointerException when parsing below yaml file:
(only paste the related snippet here)

  SiteDetail:
    allOf:
    - $ref: '#/definitions/Site'
    - type: object
      properties:
        address:
          type: string
          description: address
        **channels:
          type: array
          items:
            - $ref: '#/definitions/Channel'**

  ChannelBase:
    type: object
    properties:
      name:
        type: string
        description: channel name

  Channel:
    allOf:
    - $ref: '#/definitions/ChannelBase'
    - type: object
      properties:
        id:
          type: string
          description: channel id
          example: "10852742drp"

============================

16:39:10.492 [main] INFO  i.g.s.i.document.DefinitionsDocument - Definition processed : 'Channel'
16:39:10.542 [main] INFO  i.g.s.i.document.DefinitionsDocument - Definition processed : 'ChannelBase'
16:39:10.554 [main] INFO  i.g.s.i.document.DefinitionsDocument - Definition processed : 'Result'
16:39:10.557 [main] INFO  i.g.s.i.document.DefinitionsDocument - Definition processed : 'Site'
16:39:10.580 [main] INFO  i.g.s.i.document.DefinitionsDocument - Definition processed : 'SiteBase'
16:39:10.589 [main] INFO  i.g.s.i.document.DefinitionsDocument - Definition processed : 'SiteDetail'
Exception in thread "main" java.lang.NullPointerException
	at io.github.swagger2markup.internal.adapter.PropertyAdapter.generateExample(PropertyAdapter.java:270)
	at io.github.swagger2markup.internal.adapter.PropertyAdapter.getExample(PropertyAdapter.java:252)
	at io.github.swagger2markup.internal.component.PropertiesTableComponent.lambda$0(PropertiesTableComponent.java:104)
	at java.util.TreeMap.forEach(TreeMap.java:1005)
	at io.github.swagger2markup.internal.component.PropertiesTableComponent.apply(PropertiesTableComponent.java:96)
	at io.github.swagger2markup.internal.component.DefinitionComponent.typeSection(DefinitionComponent.java:181)
	at io.github.swagger2markup.internal.component.DefinitionComponent.apply(DefinitionComponent.java:96)
	at io.github.swagger2markup.internal.document.DefinitionsDocument.applyDefinitionComponent(DefinitionsDocument.java:168)
	at io.github.swagger2markup.internal.document.DefinitionsDocument.buildDefinition(DefinitionsDocument.java:146)
	at io.github.swagger2markup.internal.document.DefinitionsDocument.lambda$0(DefinitionsDocument.java:110)
	at java.util.TreeMap.forEach(TreeMap.java:1005)
	at io.github.swagger2markup.internal.document.DefinitionsDocument.buildDefinitionsSection(DefinitionsDocument.java:107)
	at io.github.swagger2markup.internal.document.DefinitionsDocument.apply(DefinitionsDocument.java:94)
	at io.github.swagger2markup.Swagger2MarkupConverter.applyDefinitionsDocument(Swagger2MarkupConverter.java:205)
	at io.github.swagger2markup.Swagger2MarkupConverter.toFile(Swagger2MarkupConverter.java:243)
	at io.github.swagger2markup.cli.Application.run(Application.java:84)
	at io.github.swagger2markup.cli.Application.main(Application.java:61)

[yaml.tar.gz](https://github.com/Swagger2Markup/swagger2markup/files/601330/yaml.tar.gz)

**Comment by RobWin** [comment]
Thx. I have a look at it.
If you like and use Swagger2markup, we would love to get your GitHub Star.
