### ISSUE TITLE
io.github.swagger2markup.internal.document.OverviewDocument doesn't found with swagger2markup-1.1.1.jar when generate files

### ISSUE THREAD

**Issue by zcb22000** [Swagger2Markup/swagger2markup#229]
io.github.swagger2markup.internal.document.OverviewDocument doesn't found with swagger2markup-1.1.1.jar when generate files

Swagger2Markup version:
swagger2markup-1.1.1.jar
Problem description:

```
CodegenConfigurator configurator = CodegenConfigurator.fromFile(configFile);
	new DefaultGenerator().opts(configurator.toClientOptInput()).generate();

	Path localSwaggerFile = Paths.get(yamlFile);
	Path outputFile = Paths.get(asciidocFile);		

	Swagger2MarkupConfig config = new Swagger2MarkupConfigBuilder() 
			.withPathsGroupedBy(GroupBy.TAGS)
			.withOperationOrdering(OrderBy.AS_IS)
	        .withOutputLanguage(Language.ZH) 
	        .withMarkupLanguage(MarkupLanguage.ASCIIDOC)
	        .build(); 
	Swagger2MarkupConverter.from(localSwaggerFile) 
	        .withConfig(config)
	        .build() 
	        .toFolder(outputFile);

    MarkupDocBuilder builder = MarkupDocBuilders.documentBuilder(MarkupLanguage.ASCIIDOC);
```

  it is throws java.lang.NoClassDefFoundError: javaslang/Function2 ,when i followed the code with debug mode,it is can not find the class of io.github.swagger2markup.internal.document.OverviewDocument,but it is exist in jar, and it generate ok when using swagger2markup-1.0.1.jar
   when i add: 
Class.forName("io.github.swagger2markup.internal.document.OverviewDocument"); it also throw the exception

my pom.xml is:
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>com.huawei.m2m.ecosystem.platform</groupId>
		<artifactId>rest-api</artifactId>
		<version>1.0.0</version>
	</parent>
	<artifactId>codegenerator</artifactId>

	<properties>
		<swagger-codegen.version>2.2.1</swagger-codegen.version>
	</properties>

	<dependencies>
		<dependency>
			<groupId>io.swagger</groupId>
			<artifactId>swagger-codegen</artifactId>
			<version>${swagger-codegen.version}</version>
		</dependency>

		<dependency>
			<groupId>org.apache.commons</groupId>
			<artifactId>commons-configuration2</artifactId>
			<version>2.0</version>
		</dependency>
		<dependency>
			<groupId>commons-beanutils</groupId>
			<artifactId>commons-beanutils</artifactId>
			<version>1.9.2</version>
		</dependency>
		<dependency>
			<groupId>org.apache.commons</groupId>
			<artifactId>commons-collections4</artifactId>
			<version>4.0</version>
		</dependency>
		<dependency>
			<groupId>org.pegdown</groupId>
			<artifactId>pegdown</artifactId>
			<version>1.6.0</version>
		</dependency>

		<dependency>
			<groupId>org.asciidoctor</groupId>
			<artifactId>asciidoctorj</artifactId>
			<version>1.5.4</version>
		</dependency>
		

		<dependency>
			<groupId>io.github.swagger2markup</groupId>
			<artifactId>swagger2markup</artifactId>
			<version>1.0.1</version>
			<scope>system</scope>
			<systemPath>${basedir}/lib/swagger2markup-1.1.1.jar</systemPath>
		</dependency>
		<dependency>
			<groupId>nl.jworks.markdown_to_asciidoc</groupId>
			<artifactId>markdown_to_asciidoc</artifactId>
			<version>1.0</version>
			<scope>system</scope>
			<systemPath>${basedir}/lib/markdown_to_asciidoc-1.0.jar</systemPath>
		</dependency>
		<dependency>
			<groupId>io.github.swagger2markup</groupId>
			<artifactId>markup-document-builder</artifactId>
			<version>1.1.1</version>
			<scope>system</scope>
			<systemPath>${basedir}/lib/markup-document-builder-1.1.1.jar</systemPath>
		</dependency>
		<dependency>
			<groupId>org.apache.maven.shared</groupId>
			<artifactId>maven-invoker</artifactId>
			<version>2.2</version> 
		</dependency>
	</dependencies>

	<build>
		<plugins>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-surefire-plugin</artifactId>
				<version>2.9</version>
			</plugin>
		</plugins>
	</build>

</project>

**Comment by RobWin** [comment]
Hi, thx for raising an issue.
If you like and use Swagger2markup, we would love to get your GitHub star.

Why do you use Maven and a Lib folder?
Isn't there a version mismatch?

```
<dependency>
		<groupId>io.github.swagger2markup</groupId>
		<artifactId>swagger2markup</artifactId>
		<version>1.0.1</version>
		<scope>system</scope>
		<systemPath>${basedir}/lib/swagger2markup-1.1.1.jar</systemPath>
</dependency>
```

**Comment by zcb22000** [comment]
Thanks.
We want to integrate in JAVA project not Web, and only commit yaml files which generate api files and then generate jar file and api doc.
How to do for it?
The stacktrace is:
[main] INFO io.swagger.parser.Swagger20Parser - reading from src/main/resources/yaml/nscl_test.yaml
[main] WARN io.swagger.util.PropertyDeserializer - no property from null, null, {ENUM=null, TITLE=null, DESCRIPTION=null, DEFAULT=null, PATTERN=null, DESCRIMINATOR=null, MIN_ITEMS=null, MAX_ITEMS=null, MIN_PROPERTIES=null, MAX_PROPERTIES=null, MIN_LENGTH=null, MAX_LENGTH=null, MINIMUM=null, MAXIMUM=null, EXCLUSIVE_MINIMUM=null, EXCLUSIVE_MAXIMUM=null, UNIQUE_ITEMS=null, EXAMPLE=null, TYPE=null, FORMAT=null, READ_ONLY=null, VENDOR_EXTENSIONS={}}
[main] WARN io.swagger.util.PropertyDeserializer - no property from null, null, {ENUM=null, TITLE=null, DESCRIPTION=null, DEFAULT=null, PATTERN=null, DESCRIMINATOR=null, MIN_ITEMS=null, MAX_ITEMS=null, MIN_PROPERTIES=null, MAX_PROPERTIES=null, MIN_LENGTH=null, MAX_LENGTH=null, MINIMUM=null, MAXIMUM=null, EXCLUSIVE_MINIMUM=null, EXCLUSIVE_MAXIMUM=null, UNIQUE_ITEMS=null, EXAMPLE=null, TYPE=null, FORMAT=null, READ_ONLY=null, VENDOR_EXTENSIONS={}}
Exception in thread "main" java.lang.NoClassDefFoundError: javaslang/Function2
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at io.github.swagger2markup.Swagger2MarkupConverter.<init>(Swagger2MarkupConverter.java:59)
	at io.github.swagger2markup.Swagger2MarkupConverter$Builder.build(Swagger2MarkupConverter.java:355)
	at com.huawei.m2m.ecosystem.codegen.SpringServerGenerator.generateFiles(SpringServerGenerator.java:71)
	at com.huawei.m2m.ecosystem.codegen.SpringServerGenerator.main(SpringServerGenerator.java:51)
Caused by: java.lang.ClassNotFoundException: javaslang.Function2
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 28 more

**Comment by zcb22000** [comment]
it is the same exception
		<dependency>
			<groupId>io.github.swagger2markup</groupId>
			<artifactId>swagger2markup</artifactId>
			<version>1.1.1</version>
			<scope>system</scope>
			<systemPath>${basedir}/lib/swagger2markup-1.1.1.jar</systemPath>
		</dependency>

**Comment by zcb22000** [comment]
Exception changed when using the version of 1.2.0.
It Unrecognized yaml file formal. How to use yaml files to generate api and document with 1.2.0 version?
In factually, I just want to use chinese language which does not support in 1.0.1 version.

Exeption stack:
`[main] INFO io.swagger.parser.Swagger20Parser - reading from src/main/resources/yaml/nscl_test.yaml
com.fasterxml.jackson.core.JsonParseException: Unrecognized token 'swagger': was expecting ('true', 'false' or 'null')
 at [Source: src\main\resources\yaml\nscl_test.yaml; line: 1, column: 9]
	at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1419)
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:508)
	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._reportInvalidToken(UTF8StreamJsonParser.java:3201)
	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._handleUnexpectedValue(UTF8StreamJsonParser.java:2360)
	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._nextTokenNotInObject(UTF8StreamJsonParser.java:794)
	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser.nextToken(UTF8StreamJsonParser.java:690)
	at com.fasterxml.jackson.databind.ObjectMapper._initForReading(ObjectMapper.java:3105)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3051)
	at com.fasterxml.jackson.databind.ObjectMapper.readTree(ObjectMapper.java:1861)
	at io.swagger.parser.SwaggerCompatConverter.readResourceListing(SwaggerCompatConverter.java:147)
	at io.swagger.parser.SwaggerCompatConverter.read(SwaggerCompatConverter.java:74)
	at io.swagger.parser.SwaggerParser.read(SwaggerParser.java:72)
	at io.swagger.parser.SwaggerParser.read(SwaggerParser.java:52)
	at io.github.swagger2markup.Swagger2MarkupConverter$Builder.readSwagger(Swagger2MarkupConverter.java:321)
	at io.github.swagger2markup.Swagger2MarkupConverter$Builder.<init>(Swagger2MarkupConverter.java:301)
	at io.github.swagger2markup.Swagger2MarkupConverter.from(Swagger2MarkupConverter.java:116)
	at com.huawei.m2m.ecosystem.codegen.SpringServerGenerator.generateFiles(SpringServerGenerator.java:74)
	at com.huawei.m2m.ecosystem.codegen.SpringServerGenerator.main(SpringServerGenerator.java:51)
Exception in thread "main" java.lang.IllegalArgumentException: Failed to read the Swagger source
	at io.github.swagger2markup.Swagger2MarkupConverter$Builder.readSwagger(Swagger2MarkupConverter.java:323)
	at io.github.swagger2markup.Swagger2MarkupConverter$Builder.<init>(Swagger2MarkupConverter.java:301)
	at io.github.swagger2markup.Swagger2MarkupConverter.from(Swagger2MarkupConverter.java:116)
	at com.huawei.m2m.ecosystem.codegen.SpringServerGenerator.generateFiles(SpringServerGenerator.java:74)
	at com.huawei.m2m.ecosystem.codegen.SpringServerGenerator.main(SpringServerGenerator.java:51)`

**Comment by RobWin** [comment]
Did you have a look at the template and demo projects?
https://github.com/Swagger2Markup/swagger2markup-maven-project-template

How you generate your Swagger File v2? Maybe its invalid? Can you paste it here?

**Comment by RobWin** [comment]
You need the transitive dependencies of this library, you can't just copy this library into your lib folder.
Please use Maven correctly.

**Comment by zcb22000** [comment]
OK,THANKS. There is first part of my yaml content bellow.
swagger: "2.0"

################################################################################
#                              API Information                                 #
################################################################################
info:
  version: "1.0.0"
  title:  Service REST API
  termsOfService: used for Application developing
# during dev, should point to your local machine
host: localhost
# basePath prefixes all resource paths
basePath: /myproject/app/v1.1.0
#
schemes:
  # tip: remove http to make production-grade
  # - http
  - https
# format of bodies a client can send (Content-Type)
consumes:
  - application/json
# format of the responses to the client (Accepts)
produces:
  - application/json

################################################################################
#                                  Security                                    #
################################################################################
securityDefinitions:
  app_key:
    type: apiKey
    name: app_key
    in: header
  basic_auth:
    type: basic
security:
  - app_key: []
  - basic_auth: []

paths:
  # This is a path endpoint. Change it.
  /subscriptions:
  	tags:
  	- 订阅管理
    post:
      tags:
      - 订阅管理
      x-isExistException: true
      summary: 创建订阅
      operationId: addSubscriptions
      description: |
        创建订阅
      parameters:
        -
          name: subscriptionReq
          in: body
          description: 设置订阅的内容
          required: true
          schema:
            $ref: '#/definitions/subscriptionReq'
      responses:
        200:
          description: OK
          schema:
            $ref: '#/definitions/subscription'
        400:
          description: Bad Request
        401:
          description: Unauthorized
        403:
          description: Forbidden
        404:
          description: Not Found
        500:
          description: Server Error

**Comment by zcb22000** [comment]
Sorry, it is my mistake.
I delete the project from my workspace, and import again, it is OK with group by GroupBy.AS_IS.
But it is error when GroupBy.TAGS. 
 java.lang.IllegalArgumentException: Tags must not be empty, when operations are grouped by tags

I find  issues of "https://github.com/Swagger2Markup/swagger2markup/issues/194".
And it is resolved.
Thanks.

**Comment by RobWin** [comment]
Nice

**Comment by RobWin** [comment]
Would love to get your GitHub star
