### ISSUE TITLE
text must not be null

### ISSUE THREAD

**Issue by monism** [Swagger2Markup/swagger2markup#250]
Thanks for raising a Swagger2Markup issue. Please provide a brief description of your problem along with the Swagger2Markup version you are using. If possible, please also consider putting together a complete Swagger specification that reproduces the issue. It's better if the Swagger specification is small and isolate the issue.

Swagger2Markup version:

Problem description:
2017-04-07 11:14:44.649  INFO - [main] s.s.c.s.i.SwaggerToConfluenceServiceImpl : Confluence Generate Numeric Prefixes: true
2017-04-07 11:14:44.649  INFO - [main] n.s.s.c.s.i.SwaggerToAsciiDocServiceImpl : Converting Swagger Schema to Ascii Doc...
Exception in thread "main" java.lang.IllegalArgumentException: text must not be blank
	at org.apache.commons.lang3.Validate.notBlank(Validate.java:451)
	at io.github.swagger2markup.markup.builder.internal.asciidoc.AsciiDocBuilder.paragraph(AsciiDocBuilder.java:91)
	at io.github.swagger2markup.internal.document.builder.OverviewDocumentBuilder.buildContactInfoSection(OverviewDocumentBuilder.java:127)

I am using json file which i need to publish in confluence

**Comment by RobWin** [comment]
Hi,

please create an issue in https://github.com/starlightknight/swagger-confluence.
They are using an old version of Swagger2Markup.
