### ISSUE TITLE
title must not be blank

### ISSUE THREAD

**Issue by abhijiths148** [Swagger2Markup/swagger2markup#252]
```
Exception in thread "main" java.lang.NullPointerException: title must not be blank
	at org.apache.commons.lang3.Validate.notBlank(Validate.java:451)
	at io.github.swagger2markup.markup.builder.internal.AbstractMarkupDocBuilder.documentTitle(AbstractMarkupDocBuilder.java:91)
	at io.github.swagger2markup.markup.builder.internal.asciidoc.AsciiDocBuilder.documentTitle(AsciiDocBuilder.java:73)
	at io.github.swagger2markup.internal.document.builder.OverviewDocumentBuilder.buildDocumentTitle(OverviewDocumentBuilder.java:100)
	at io.github.swagger2markup.internal.document.builder.OverviewDocumentBuilder.build(OverviewDocumentBuilder.java:82)
	at io.github.swagger2markup.Swagger2MarkupConverter.toFolder(Swagger2MarkupConverter.java:174)
```

Any idea on why this is occuring, i am using dropwizard-swagger https://github.com/smoketurner/dropwizard-swagger

**Comment by RobWin** [comment]
Which version of swagger2markup do you use?

**Comment by abhijiths148** [comment]
compile group: 'io.github.swagger2markup', name: 'swagger2markup', version: '1.1.0'

**Comment by RobWin** [comment]
Could you update to the latest version? This should be fixed

**Comment by abhijiths148** [comment]
hi i tried version 1.3.1 as well but no success

**Comment by RobWin** [comment]
Can you fill the title of the Swagger Spec?
https://github.com/smoketurner/dropwizard-swagger/blob/master/src/main/java/io/federecio/dropwizard/swagger/SwaggerBundleConfiguration.java#L85

**Comment by abhijiths148** [comment]
Thanks,
added title by providing this on my resource class it seemed to work
```
@SwaggerDefinition(info = @Info(description = "My API", version = "1.1.0-1",title = "Swagger"))
```

**Comment by huihaoweishui** [comment]
@abhijiths148  what is resource class
