### ISSUE TITLE
NoClassDefFound in docker image

### ISSUE THREAD

**Issue by jimmiebtlr** [Swagger2Markup/swagger2markup#257]
Thanks for raising a Swagger2Markup issue. Please provide a brief description of your problem along with the Swagger2Markup version you are using. If possible, please also consider putting together a complete Swagger specification that reproduces the issue. It's better if the Swagger specification is small and isolate the issue.

Swagger2Markup version:
https://hub.docker.com/r/swagger2markup/swagger2markup/

Problem description:
The docker container fails to run due to error.

```
12:58:40.168 [main] INFO  io.swagger.parser.Swagger20Parser - reading from /opt/services/identity/privrouter/swagger/swagger.json
12:58:40.473 [main] DEBUG i.s.m.properties.PropertyBuilder - no property for null, null
12:58:40.474 [main] WARN  io.swagger.util.PropertyDeserializer - no property from null, null, {ENUM=null, TITLE=null, DESCRIPTION=null, DEFAULT=null, PATTERN=null, DESCRIMINATOR=null, MIN_ITEMS=null, MAX_ITEMS=null, MIN_PROPERTIES=null, MAX_PROPERTIES=null, MIN_LENGTH=null, MAX_LENGTH=null, MINIMUM=null, MAXIMUM=null, EXCLUSIVE_MINIMUM=null, EXCLUSIVE_MAXIMUM=null, UNIQUE_ITEMS=null, EXAMPLE=John, TYPE=null, FORMAT=null, READ_ONLY=null, VENDOR_EXTENSIONS={}, MULTIPLE_OF=null}
Exception in thread "main" java.lang.NoClassDefFoundError: javaslang/λ
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at io.github.swagger2markup.Swagger2MarkupConverter.<init>(Swagger2MarkupConverter.java:59)
	at io.github.swagger2markup.Swagger2MarkupConverter$Builder.build(Swagger2MarkupConverter.java:353)
	at io.github.swagger2markup.cli.Application.run(Application.java:81)
	at io.github.swagger2markup.cli.Application.main(Application.java:61)
Caused by: java.lang.ClassNotFoundException: javaslang.λ
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 40 more
```

**Comment by ethack** [comment]
I'm getting the same error.  Seems to be related to [this issue](https://github.com/Swagger2Markup/swagger2markup-cli/issues/15)?

**Comment by RobWin** [comment]
Hi @ethack @jimmiebtlr 
Sry that it took some time. I've been on vacation.
I published v1.3.2.
Could you please try if the new image works for you?

**Comment by RobWin** [comment]
It works for me
```
ocker run --rm -v $(pwd):/opt swagger2markup/swagger2markup:1.3.2 convert -i /opt/swagger_petstore.yaml -f /opt/swagger
08:06:41.582 [main] INFO  io.swagger.parser.Swagger20Parser - reading from /opt/swagger_petstore.yaml
08:06:42.480 [main] INFO  i.g.s.m.b.i.asciidoc.AsciiDocBuilder - Markup document written to: /opt/swagger.adoc
08:06:42.483 [main] INFO  i.g.s.m.b.i.asciidoc.AsciiDocBuilder - Markup document written to: /opt/swagger.adoc
```

**Comment by ethack** [comment]
That worked, thank you!

**Comment by RobWin** [comment]
@jimmiebtlr For you as well?
