### ISSUE TITLE
Getting java.lang.NoSuchFieldError: MULTIPLE_OF while creating Asscidocs

### ISSUE THREAD

**Issue by angsdey2** [Swagger2Markup/swagger2markup#273]
I am converting a swagger json to asciidoc to covert it to html, by the below way 

pom.xml
----------
`<dependency>
        <groupId>io.github.swagger2markup</groupId>
        <artifactId>swagger2markup</artifactId>
        <version>1.3.1</version>
</dependency>`

Conversion
------------
`String contents = new String(Files.readAllBytes(Paths.get("C://temp_json.json")));
Path path = Paths.get("C://asciidoc");
Swagger2MarkupConverter.from(contents).build().toFolder(path);`

But unfortunately getting the below error while parsing.

Exception in thread "main" java.lang.NoSuchFieldError: MULTIPLE_OF
	at io.swagger.util.PropertyDeserializer.argsFromNode(PropertyDeserializer.java:196)
	at io.swagger.util.PropertyDeserializer.propertyFromNode(PropertyDeserializer.java:304)
	at io.swagger.util.PropertyDeserializer.deserialize(PropertyDeserializer.java:137)
	at io.swagger.util.PropertyDeserializer.deserialize(PropertyDeserializer.java:39)

Nay help will appreciated.

**Comment by RobWin** [comment]
Hi,
This seems to be an an issue of the swagger-parser and not Swagger2Markup.
But I can't help you without a possibility to reproduce the issue.

**Comment by johnnywong233** [comment]
@angsdey2 I wander have you fixed your problem? Now I met the same error as yours, so any help is very appreciated. thanks!
