### ISSUE TITLE
Unable to load RELATIVE ref: ./parameters.yaml

### ISSUE THREAD

**Issue by neuneuraxis** [Swagger2Markup/swagger2markup#276]
I'm starting with gradle plugin swagger2markup version 13.1.

I have this directory structure: 
```
- models
      |_ main.yaml
      |_ components
            |_ parameters.yaml
            |_ paths.yaml
- build.gradle 
```
The _main.yml_ references _paths.yaml_ and _paths.yaml_ references _parameters.yaml_.
When I launch the task `convertSwagger2markup --stacktrace`, I have this error:
```
Caused by: java.lang.RuntimeException: Unable to load RELATIVE ref: ./parameters.yaml
        at io.swagger.parser.util.RefUtils.readExternalRef(RefUtils.java:140)
        at io.swagger.parser.ResolverCache.loadRef(ResolverCache.java:94)
        at io.swagger.parser.processors.ParameterProcessor.processParameters(ParameterProcessor.java:37)
        at io.swagger.parser.processors.OperationProcessor.processOperation(OperationProcessor.java:26)
        at io.swagger.parser.processors.PathsProcessor.processPaths(PathsProcessor.java:93)
        at io.swagger.parser.SwaggerResolver.resolve(SwaggerResolver.java:40)
        at io.swagger.parser.SwaggerParser.read(SwaggerParser.java:66)
        at io.swagger.parser.SwaggerParser.read(SwaggerParser.java:52)
        at io.github.swagger2markup.Swagger2MarkupConverter$Builder.readSwagger(Swagger2MarkupConverter.java:321)
        at io.github.swagger2markup.Swagger2MarkupConverter$Builder.<init>(Swagger2MarkupConverter.java:301)
        at io.github.swagger2markup.Swagger2MarkupConverter.from(Swagger2MarkupConverter.java:116)
        at io.github.swagger2markup.Swagger2MarkupConverter.from(Swagger2MarkupConverter.java:81)
        at io.github.swagger2markup.Swagger2MarkupConverter$from.call(Unknown Source)
        at io.github.swagger2markup.tasks.Swagger2MarkupTask.convertSwagger2markup(Swagger2MarkupTask.groovy:62)
```

**Comment by RobWin** [comment]
Hi, please open an issue in https://github.com/swagger-api/swagger-parser
It's not an issue of Swagger2Markup itself.
