### ISSUE TITLE
NullPointerException when using $ref in schema

### ISSUE THREAD

**Issue by kaos** [Swagger2Markup/swagger2markup#288]
Version: 1.3.1

Minified spec to reproduce issue:

```
$ java -jar ../swagger2markup-cli/build/libs/swagger2markup-cli-1.3.1.jar convert -i spectest.json -d tmp
23:52:11.581 [main] INFO  io.swagger.parser.Swagger20Parser - reading from /Users/aadt/Src/kaos/github/swagger-confluence/spectest.json
23:52:12.658 [main] DEBUG i.s.m.properties.PropertyBuilder - no property for null, null
23:52:12.659 [main] WARN  io.swagger.util.PropertyDeserializer - no property from null, null, {ENUM=null, TITLE=null, DESCRIPTION=null, DEFAULT=null, PATTERN=null, DESCRIMINATOR=null, MIN_ITEMS=null, MAX_ITEMS=null, MIN_PROPERTIES=null, MAX_PROPERTIES=null, MIN_LENGTH=null, MAX_LENGTH=null, MINIMUM=null, MAXIMUM=null, EXCLUSIVE_MINIMUM=null, EXCLUSIVE_MAXIMUM=null, UNIQUE_ITEMS=null, EXAMPLE=null, TYPE=null, FORMAT=null, READ_ONLY=null, VENDOR_EXTENSIONS={}, MULTIPLE_OF=null}
23:52:12.660 [main] DEBUG i.s.m.properties.PropertyBuilder - no property for null, null
23:52:12.660 [main] WARN  io.swagger.util.PropertyDeserializer - no property from null, null, {ENUM=null, TITLE=null, DESCRIPTION=A list of MIME types accepted by the API., DEFAULT=null, PATTERN=null, DESCRIMINATOR=null, MIN_ITEMS=null, MAX_ITEMS=null, MIN_PROPERTIES=null, MAX_PROPERTIES=null, MIN_LENGTH=null, MAX_LENGTH=null, MINIMUM=null, MAXIMUM=null, EXCLUSIVE_MINIMUM=null, EXCLUSIVE_MAXIMUM=null, UNIQUE_ITEMS=null, EXAMPLE=null, TYPE=null, FORMAT=null, READ_ONLY=null, VENDOR_EXTENSIONS={}, MULTIPLE_OF=null}
23:52:12.660 [main] DEBUG i.s.m.properties.PropertyBuilder - no property for null, null
23:52:12.660 [main] WARN  io.swagger.util.PropertyDeserializer - no property from null, null, {ENUM=null, TITLE=null, DESCRIPTION=A list of MIME types the API can produce., DEFAULT=null, PATTERN=null, DESCRIMINATOR=null, MIN_ITEMS=null, MAX_ITEMS=null, MIN_PROPERTIES=null, MAX_PROPERTIES=null, MIN_LENGTH=null, MAX_LENGTH=null, MINIMUM=null, MAXIMUM=null, EXCLUSIVE_MINIMUM=null, EXCLUSIVE_MAXIMUM=null, UNIQUE_ITEMS=null, EXAMPLE=null, TYPE=null, FORMAT=null, READ_ONLY=null, VENDOR_EXTENSIONS={}, MULTIPLE_OF=null}
Exception in thread "main" java.lang.NullPointerException
	at io.swagger.parser.util.SwaggerDeserializer.definition(SwaggerDeserializer.java:763)
	at io.swagger.parser.ResolverCache.loadRef(ResolverCache.java:123)
	at io.swagger.parser.processors.ExternalRefProcessor.processRefToExternalDefinition(ExternalRefProcessor.java:34)
	at io.swagger.parser.processors.ExternalRefProcessor.processRefProperty(ExternalRefProcessor.java:113)
	at io.swagger.parser.processors.ExternalRefProcessor.processRefToExternalDefinition(ExternalRefProcessor.java:77)
	at io.swagger.parser.processors.PropertyProcessor.processRefProperty(PropertyProcessor.java:34)
	at io.swagger.parser.processors.PropertyProcessor.processProperty(PropertyProcessor.java:21)
	at io.swagger.parser.processors.ResponseProcessor.processResponse(ResponseProcessor.java:21)
	at io.swagger.parser.processors.OperationProcessor.processOperation(OperationProcessor.java:45)
	at io.swagger.parser.processors.PathsProcessor.processPaths(PathsProcessor.java:93)
	at io.swagger.parser.SwaggerResolver.resolve(SwaggerResolver.java:40)
	at io.swagger.parser.SwaggerParser.read(SwaggerParser.java:66)
	at io.swagger.parser.SwaggerParser.read(SwaggerParser.java:52)
	at io.github.swagger2markup.Swagger2MarkupConverter$Builder.readSwagger(Swagger2MarkupConverter.java:321)
	at io.github.swagger2markup.Swagger2MarkupConverter$Builder.<init>(Swagger2MarkupConverter.java:301)
	at io.github.swagger2markup.Swagger2MarkupConverter.from(Swagger2MarkupConverter.java:116)
	at io.github.swagger2markup.Swagger2MarkupConverter.from(Swagger2MarkupConverter.java:81)
	at io.github.swagger2markup.cli.Application.run(Application.java:77)
	at io.github.swagger2markup.cli.Application.main(Application.java:61)
$ cat spectest.json 
{
  "info": {
    "version": "1.0.17.post489",
    "description": "Continuous Deployment Interfaces, API gateway with service discovery",
    "title": "CDI Server (TEST)"
  },
  "basePath": "/",
  "swagger": "2.0",
  "paths": {
    "/swagger/spec": {
      "get": {
        "description": "<br/>Provides a merged spec based on all published swagger specs<br/>from the services discovered in zookeeper.<br/>",
        "summary": "Get swagger spec for all discovered services.",
        "responses": {
          "200": {
            "description": "returns the swagger spec in json format.",
            "schema": {
              "$ref": "https://raw.githubusercontent.com/OAI/OpenAPI-Specification/master/schemas/v2.0/schema.json"
            }
          }
        },
        "tags": [
          "swagger"
        ]
      }
    }
  }
}
```

related to #213

**Comment by RobWin** [comment]
Hi, sry for the late reply.
The NPE is thrown in the swagger-parser library. Please open a bug here: https://github.com/swagger-api/swagger-parser
