### ISSUE TITLE
NPE on Spring Boots /env POST endpoint

### ISSUE THREAD

**Issue by MahatmaFatalError** [Swagger2Markup/swagger2markup#305]
Swagger2Markup version: 1.3.2

Problem description:
swagger2markup-maven-plugin (1.3.4) in combination with swagger2markup-import-files-ext (1.3.1) can not deal with the /env endpoint description generated by springfox-swagger2 (2.8.0), which is a standard spring boot (1.5.2.RELEASE) endpoint.

Excerpt from swagger.json
`"/env": {
         "post": {
            "tags": [
               "environment-manager-mvc-endpoint"
            ],
            "summary": "value",
            "operationId": "valueUsingPOST",
            "consumes": [
               "application/json"
            ],
            "produces": [
               "*/*"
            ],
            "parameters": [
               {
                  "name": "params",
                  "in": "query",
                  "description": "params",
                  "required": true,
                  "items": {
                     "type": "object",
                     "additionalProperties": {
                        "type": "string"
                     }
                  }
               }
            ],
            "responses": {
               "200": {
                  "description": "OK",
                  "schema": {
                     "type": "object"
                  }
               },
               "201": {
                  "description": "Created"
               },
               "401": {
                  "description": "Unauthorized"
               },
               "403": {
                  "description": "Forbidden"
               },
               "404": {
                  "description": "Not Found"
               }
            }
         }
      },`

Stacktrace:
`Caused by: java.lang.NullPointerException: Type of parameter 'params' must not be blank
	at org.apache.commons.lang3.Validate.notBlank(Validate.java:448)
	at io.github.swagger2markup.internal.type.BasicType.<init>(BasicType.java:41)
	at io.github.swagger2markup.internal.adapter.ParameterAdapter.getType(ParameterAdapter.java:176)
	at io.github.swagger2markup.internal.adapter.ParameterAdapter.<init>(ParameterAdapter.java:57)
	at io.github.swagger2markup.internal.component.ParameterTableComponent.apply(ParameterTableComponent.java:91)
	at io.github.swagger2markup.internal.component.PathOperationComponent.buildParametersSection(PathOperationComponent.java:198)
	at io.github.swagger2markup.internal.component.PathOperationComponent.apply(PathOperationComponent.java:100)
	at io.github.swagger2markup.internal.document.PathsDocument.applyPathOperationComponent(PathsDocument.java:223)
	at io.github.swagger2markup.internal.document.PathsDocument.buildOperation(PathsDocument.java:207)
	at io.github.swagger2markup.internal.document.PathsDocument.lambda$null$1(PathsDocument.java:133)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at io.github.swagger2markup.internal.document.PathsDocument.lambda$buildsPathsSection$2(PathsDocument.java:133)
	at java.util.TreeMap.forEach(TreeMap.java:1005)
	at io.github.swagger2markup.internal.document.PathsDocument.buildsPathsSection(PathsDocument.java:127)
	at io.github.swagger2markup.internal.document.PathsDocument.apply(PathsDocument.java:103)
	at io.github.swagger2markup.Swagger2MarkupConverter.applyPathsDocument(Swagger2MarkupConverter.java:197)
	at io.github.swagger2markup.Swagger2MarkupConverter.toFolder(Swagger2MarkupConverter.java:182)
	at io.github.swagger2markup.Swagger2MarkupMojo.swaggerToMarkup(Swagger2MarkupMojo.java:106)
	at io.github.swagger2markup.Swagger2MarkupMojo.execute(Swagger2MarkupMojo.java:86)`

**Comment by RobWin** [comment]
Yes, seems that the env endpoint is not valid. The type is missing.
Must be `"type": "array"` I guess.

**Comment by MahatmaFatalError** [comment]
So what does this mean? Bug in springfox-swagger2 or what?

**Comment by Jannis87** [comment]
Same here. Is there a way to fix this? 
Swagger2Markup would be very useful for me.
