### ISSUE TITLE
Exception: org.objectweb.asm.tree.ClassNode has interface org.objectweb.asm.ClassVisitor as super class

### ISSUE THREAD

**Issue by p4535992** [Swagger2Markup/swagger2markup#325]
Strange exception on  a run of a simple project.

Swagger2Markup version:
Release 1.3.3

Problem description:

I follow the documentation on the link http://swagger2markup.github.io/swagger2markup/1.3.3/ for the last release 1.3.3. I create a simple maven project and added the depedency:
```xml
		<dependency>
		    <groupId>io.github.swagger2markup</groupId>
		    <artifactId>swagger2markup</artifactId>
		    <version>1.3.3</version>
		</dependency>
```

When try to run the simple code below , i get a exception:

```java
	public static void main(String[] args) {
		Path localSwaggerFile = new File("C:\\Users\\Pancio\\Desktop\\kalliphant\\FirmaRemota.yaml").toPath();
		Path outputDirectory = new File("C:\\Users\\Pancio\\Desktop\\kalliphant\\outputDoc").toPath();

		Swagger2MarkupConverter.from(localSwaggerFile) 
		        .build() 
		        .toFolder(outputDirectory); 

	}
```
the exception
```
Exception in thread "main" java.lang.IncompatibleClassChangeError: class org.objectweb.asm.tree.ClassNode has interface org.objectweb.asm.ClassVisitor as super class
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at org.parboiled.transform.ParserTransformer.extendParserClass(ParserTransformer.java:43)
	at org.parboiled.transform.ParserTransformer.transformParser(ParserTransformer.java:38)
	at org.parboiled.Parboiled.createParser(Parboiled.java:54)
	at org.pegdown.PegDownProcessor.<init>(PegDownProcessor.java:92)
	at org.pegdown.PegDownProcessor.<init>(PegDownProcessor.java:61)
	at nl.jworks.markdown_to_asciidoc.Converter.convertMarkdownToAsciiDoc(Converter.java:42)
	at io.github.swagger2markup.markup.builder.internal.AbstractMarkupDocBuilder.convert(AbstractMarkupDocBuilder.java:415)
	at io.github.swagger2markup.markup.builder.internal.AbstractMarkupDocBuilder.importMarkupStyle1(AbstractMarkupDocBuilder.java:452)
	at io.github.swagger2markup.markup.builder.internal.asciidoc.AsciiDocBuilder.importMarkup(AsciiDocBuilder.java:257)
	at io.github.swagger2markup.markup.builder.internal.AbstractMarkupDocBuilder.importMarkup(AbstractMarkupDocBuilder.java:407)
	at io.github.swagger2markup.internal.utils.MarkupDocBuilderUtils.markupDescription(MarkupDocBuilderUtils.java:67)
	at io.github.swagger2markup.internal.component.DefinitionComponent.apply(DefinitionComponent.java:79)
	at io.github.swagger2markup.internal.document.DefinitionsDocument.applyDefinitionComponent(DefinitionsDocument.java:160)
	at io.github.swagger2markup.internal.document.DefinitionsDocument.buildDefinition(DefinitionsDocument.java:138)
	at io.github.swagger2markup.internal.document.DefinitionsDocument.lambda$buildDefinitionsSection$0(DefinitionsDocument.java:102)
	at java.util.TreeMap.forEach(TreeMap.java:1005)
	at io.github.swagger2markup.internal.document.DefinitionsDocument.buildDefinitionsSection(DefinitionsDocument.java:99)
	at io.github.swagger2markup.internal.document.DefinitionsDocument.apply(DefinitionsDocument.java:86)
	at io.github.swagger2markup.Swagger2MarkupConverter.applyDefinitionsDocument(Swagger2MarkupConverter.java:203)
	at io.github.swagger2markup.Swagger2MarkupConverter.toFolder(Swagger2MarkupConverter.java:184)
	at it.abd.utility.test.yaml.Yaml2Java1.main(Yaml2Java1.java:17)
```

**Comment by RobWin** [comment]
Hi, I think I've seen this exception before. It happens when there is another maven/gradle plugin which uses a different version of [ASM](https://asm.ow2.io/).

**Comment by p4535992** [comment]
You are right, only a detail it wasn't a plugin but a other dependency (i will try to found out which one).
I close the ticket because the code standalone has worked.
