### ISSUE TITLE
Swagger2Markup 1.3.3 java.lang.NoSuchMethodError: 

### ISSUE THREAD

**Issue by xp0028** [Swagger2Markup/swagger2markup#326]
Swagger2Markup version:
1.3.3
Problem description:
java.lang.NoSuchMethodError: io.swagger.models.Response.responseSchema(Lio/swagger/models/Model;)Lio/swagger/models/Response;

	at io.swagger.parser.util.SwaggerDeserializer.response(SwaggerDeserializer.java:1108)
	at io.swagger.parser.util.SwaggerDeserializer.responses(SwaggerDeserializer.java:1067)
	at io.swagger.parser.util.SwaggerDeserializer.operation(SwaggerDeserializer.java:341)
	at io.swagger.parser.util.SwaggerDeserializer.path(SwaggerDeserializer.java:237)
	at io.swagger.parser.util.SwaggerDeserializer.paths(SwaggerDeserializer.java:188)
	at io.swagger.parser.util.SwaggerDeserializer.parseRoot(SwaggerDeserializer.java:109)
	at io.swagger.parser.util.SwaggerDeserializer.deserialize(SwaggerDeserializer.java:39)
	at io.swagger.parser.Swagger20Parser.convertToSwagger(Swagger20Parser.java:136)
	at io.swagger.parser.Swagger20Parser.read(Swagger20Parser.java:105)
	at io.swagger.parser.SwaggerParser.read(SwaggerParser.java:69)
	at io.swagger.parser.SwaggerParser.read(SwaggerParser.java:58)
	at io.github.swagger2markup.Swagger2MarkupConverter$Builder.readSwagger(Swagger2MarkupConverter.java:321)
	at io.github.swagger2markup.Swagger2MarkupConverter$Builder.<init>(Swagger2MarkupConverter.java:291)
	at io.github.swagger2markup.Swagger2MarkupConverter.from(Swagger2MarkupConverter.java:95)
	at com.dxy.tag.TagSampleApplicationTests.generateAsciiDocs(TagSampleApplicationTests.java:23)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.springframework.test.context.junit4.statements.RunBeforeTestMethodCallbacks.evaluate(RunBeforeTestMethodCallbacks.java:75)
	at org.springframework.test.context.junit4.statements.RunAfterTestMethodCallbacks.evaluate(RunAfterTestMethodCallbacks.java:86)
	at org.springframework.test.context.junit4.statements.SpringRepeat.evaluate(SpringRepeat.java:84)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:252)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:94)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.springframework.test.context.junit4.statements.RunBeforeTestClassCallbacks.evaluate(RunBeforeTestClassCallbacks.java:61)
	at org.springframework.test.context.junit4.statements.RunAfterTestClassCallbacks.evaluate(RunAfterTestClassCallbacks.java:70)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.run(SpringJUnit4ClassRunner.java:191)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:51)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)

**Comment by RobWin** [comment]
Sry. Issue is unclear to me.

**Comment by dcp65** [comment]
I am getting the same issue with Swagger2Markup 1.3.3.

**Comment by micobarac** [comment]
Non of the above solutions worked for me :(.

**Comment by pinfrederic** [comment]
Same for me. That's not working

**Comment by austek** [comment]
@pinfrederic could you provide more information?
