### ISSUE TITLE
swagger2markup

### ISSUE THREAD

**Issue by Hackniu** [Swagger2Markup/swagger2markup#332]
Thanks for raising a Swagger2Markup issue. Please provide a brief description of your problem along with the Swagger2Markup version you are using. If possible, please also consider putting together a complete Swagger specification that reproduces the issue. It's better if the Swagger specification is small and isolate the issue.

Swagger2Markup version:

Problem description:
I want to generate swagger in pdf, so I use swagger2markup. I followed the documentation in http://swagger2markup.github.io/swagger2markup/1.3.1/
in 3.1.2 conversion of a remote swagger file section, I used the code below to generate swagger.adoc in build/asciidoc directory
URL remoteSwaggerFile = new URL("http://petstore.swagger.io/v2/swagger.json");
Path outputDirectory = Paths.get("build/asciidoc");

Swagger2MarkupConverter.from(remoteSwaggerFile) 
        .build() 
        .toFolder(outputDirectory);

Also, I use 
<dependency>
            <groupId>ca.szc.thirdparty.nl.jworks.markdown_to_asciidoc</groupId>
            <artifactId>markdown_to_asciidoc</artifactId>
            <version>1.0</version>
        </dependency>
        <dependency>
            <groupId>org.asciidoctor</groupId>
            <artifactId>asciidoctorj</artifactId>
            <version>1.5.6</version>
        </dependency>
        <dependency>
            <groupId>org.apache.httpcomponents</groupId>
            <artifactId>httpclient</artifactId>
            <version>4.5.2</version>
        </dependency>
        <dependency>
            <groupId>io.github.swagger2markup</groupId>
            <artifactId>swagger2markup</artifactId>
            <version>1.3.1</version>
        </dependency>

It doesn't work as expect, it show : 
java.lang.ClassNotFoundException: ch.netzwerg.paleo.ColumnIds$StringColumnId
at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[na:1.8.0_171]
at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[na:1.8.0_171]
at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349) ~[na:1.8.0_171]
at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[na:1.8.0_171]
at io.github.swagger2markup.internal.component.ParameterTableComponent.apply(ParameterTableComponent.java:76) ~[swagger2markup-1.3.1.jar:1.3.1]
at io.github.swagger2markup.internal.component.PathOperationComponent.buildParametersSection(PathOperationComponent.java:198) ~[swagger2markup-1.3.1.jar:1.3.1]
at io.github.swagger2markup.internal.component.PathOperationComponent.apply(PathOperationComponent.java:100) ~[swagger2markup-1.3.1.jar:1.3.1]
at io.github.swagger2markup.internal.document.PathsDocument.applyPathOperationComponent(PathsDocument.java:223) ~[swagger2markup-1.3.1.jar:1.3.1]
at io.github.swagger2markup.internal.document.PathsDocument.buildOperation(PathsDocument.java:207) ~[swagger2markup-1.3.1.jar:1.3.1]
at io.github.swagger2markup.internal.document.PathsDocument.lambda$buildsPathsSection$0(PathsDocument.java:119) ~[swagger2markup-1.3.1.jar:1.3.1]

Anyone knows how swagger2markup works, please help, thx!

**Comment by eranation** [comment]
make sure you add the needed repositories, e.g.

```xml
<repositories>
    <repository>
        <snapshots>
            <enabled>false</enabled>
        </snapshots>
        <id>jcenter-releases</id>
        <name>jcenter</name>
        <url>http://jcenter.bintray.com</url>
    </repository>
</repositories>
```

**Comment by austek** [comment]
Closing, https://github.com/Swagger2Markup/swagger2markup/issues/332#issuecomment-483905345 should address the issue
