### ISSUE TITLE
cli error java.lang.NullPointerException: text must not be blank

### ISSUE THREAD

**Issue by Xib1uvXi** [Swagger2Markup/swagger2markup#335]
Swagger2Markup version:

1.3.3
swagger2markup-cli-1.3.3.jar

Problem description:
run cmd:

```shell
java -jar swagger2markup-cli-1.3.3.jar convert -i "http://localhost:8089/swagger-ui/api-doc.json" -f api/api -c config.properties
```
get Exception in thread "main" java.lang.NullPointerException: text must not be blank

error detail:

```test
15:26:51.805 [main] INFO  io.swagger.parser.Swagger20Parser - reading from http://localhost:8089/swagger-ui/api-doc.json
15:26:52.007 [main] DEBUG i.g.s.i.document.PathsDocument - Generate examples is disabled.
15:26:52.007 [main] DEBUG i.g.s.i.document.PathsDocument - Create separated operation files is disabled.
15:26:52.007 [main] DEBUG i.g.s.i.document.DefinitionsDocument - Create separated definition files is disabled.
15:26:52.027 [main] INFO  i.g.s.m.b.i.markdown.MarkdownBuilder - Markup document written to: /home/qydev/go/src/chainstack-monitor/monitor/api/api.md
Exception in thread "main" java.lang.NullPointerException: text must not be blank
	at org.apache.commons.lang3.Validate.notBlank(Validate.java:448)
	at io.github.swagger2markup.markup.builder.internal.AbstractMarkupDocBuilder.boldTextLine(AbstractMarkupDocBuilder.java:296)
	at io.github.swagger2markup.internal.component.ParameterTableComponent.getParameterNameColumnContent(ParameterTableComponent.java:126)
	at io.github.swagger2markup.internal.component.ParameterTableComponent.apply(ParameterTableComponent.java:97)
	at io.github.swagger2markup.internal.component.PathOperationComponent.buildParametersSection(PathOperationComponent.java:198)
	at io.github.swagger2markup.internal.component.PathOperationComponent.apply(PathOperationComponent.java:100)
	at io.github.swagger2markup.internal.document.PathsDocument.applyPathOperationComponent(PathsDocument.java:223)
	at io.github.swagger2markup.internal.document.PathsDocument.buildOperation(PathsDocument.java:207)
	at io.github.swagger2markup.internal.document.PathsDocument.lambda$buildsPathsSection$0(PathsDocument.java:119)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at io.github.swagger2markup.internal.document.PathsDocument.buildsPathsSection(PathsDocument.java:119)
	at io.github.swagger2markup.internal.document.PathsDocument.apply(PathsDocument.java:103)
	at io.github.swagger2markup.Swagger2MarkupConverter.applyPathsDocument(Swagger2MarkupConverter.java:197)
	at io.github.swagger2markup.Swagger2MarkupConverter.toFile(Swagger2MarkupConverter.java:240)
	at io.github.swagger2markup.cli.Application.run(Application.java:84)
	at io.github.swagger2markup.cli.Application.main(Application.java:61)
```
swagger web is running and no error

curl http://localhost:8089/swagger-ui/api-doc.json 
get output:

```json
{
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "description": "Chainstack Monitor API",
    "title": "monitor API.",
    "contact": {
      "name": "Ox Star Star",
      "email": "wangxi@chainstack.io"
    },
    "version": "0.0.1"
  },
  "host": "localhost:8080",
  "basePath": "/api",
  "paths": {
    "/chainstack_nodes": {
      "get": {
        "description": "这里可以得到所有上报过的节点的最新数据",
        "tags": [
          "节点监控"
        ],
        "summary": "获取所有节点上报的数据",
        "operationId": "data",
        "responses": {
          "200": {
            "$ref": "#/responses/getNodesResp"
          }
        }
      },
      "post": {
        "description": "上报节点的最新数据",
        "tags": [
          "数据上报"
        ],
        "summary": "上报节点数据",
        "operationId": "data",
        "parameters": [
          {
            "description": "Msg",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/Msg"
            }
          }
        ],
        "responses": {
          "200": {
            "$ref": "#/responses/baseResp"
          }
        }
      }
    },
    "/record/{node_id}": {
      "get": {
        "description": "这里可以得到节点上报过的风险记录",
        "tags": [
          "节点监控"
        ],
        "summary": "获取节点的风险记录",
        "operationId": "data",
        "parameters": [
          {
            "description": "节点id",
            "name": "node_id",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            }
          },
          {
            "description": "风险类型",
            "name": "risk_type",
            "in": "query",
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "$ref": "#/responses/getNodeRiskRecordResp"
          }
        }
      }
    }
  },
  "definitions": {
    "BlockInfo": {
      "type": "object",
      "properties": {
        "block_hash": {
          "description": "区块hash",
          "type": "string",
          "x-go-name": "BlockHash"
        },
        "block_height": {
          "description": "区块高度",
          "type": "integer",
          "format": "uint64",
          "x-go-name": "BlockNumHeight"
        },
        "block_time": {
          "description": "区块时间",
          "type": "string",
          "x-go-name": "BlockTime"
        },
        "block_transactions": {
          "description": "区块交易数",
          "type": "integer",
          "format": "int64",
          "x-go-name": "BlockTransactions"
        },
        "difficulty": {
          "description": "区块难度值",
          "type": "string",
          "x-go-name": "Difficulty"
        }
      },
      "x-go-package": "chainstack-monitor/monitor/model"
    },
    "ChainstackNode": {
      "description": "节点列表",
      "type": "object",
      "properties": {
        "last_collect_data": {
          "$ref": "#/definitions/NodeCollectData"
        },
        "node_id": {
          "description": "节点id",
          "type": "string",
          "x-go-name": "NodeID"
        }
      },
      "x-go-package": "chainstack-monitor/monitor/model"
    },
    "Msg": {
      "type": "object",
      "properties": {
        "msg": {
          "type": "object",
          "x-go-name": "Msg"
        },
        "msg_time": {
          "type": "string",
          "format": "date-time",
          "x-go-name": "MsgTime"
        },
        "msg_type": {
          "type": "string",
          "x-go-name": "MsgType"
        }
      },
      "x-go-package": "chainstack-monitor/collector/model"
    },
    "NodeCollectData": {
      "description": "节点采集的数据",
      "type": "object",
      "properties": {
        "address": {
          "description": "节点默认的地址",
          "type": "string",
          "x-go-name": "Address"
        },
        "base_peer_list": {
          "description": "节点连接的普通节点",
          "type": "array",
          "items": {
            "type": "string"
          },
          "x-go-name": "BasePeerList"
        },
        "chain_version": {
          "description": "采集时节点采用的链版本",
          "type": "string",
          "x-go-name": "ChainVersion"
        },
        "current_difficulty": {
          "description": "采集时节点最后一个块的难度值",
          "type": "string",
          "x-go-name": "CurrentDifficulty"
        },
        "http_port": {
          "description": "节点 http监听端口",
          "type": "string",
          "x-go-name": "HttpPort"
        },
        "id": {
          "description": "全局唯一id",
          "type": "string",
          "x-go-name": "ID"
        },
        "is_alive": {
          "description": "是否存活",
          "type": "boolean",
          "x-go-name": "IsAlive"
        },
        "is_miner_master": {
          "description": "是否是矿工头",
          "type": "boolean",
          "x-go-name": "IsMinerMaster"
        },
        "is_verifier": {
          "description": "是否是验证者",
          "type": "boolean",
          "x-go-name": "IsVerifier"
        },
        "last_appear": {
          "description": "采集时的时间",
          "type": "string",
          "format": "date-time",
          "x-go-name": "LastAppear"
        },
        "last_block_hash": {
          "description": "采集时节点最后一个块的Hash",
          "type": "string",
          "x-go-name": "LastBlockHash"
        },
        "last_block_height": {
          "description": "采集时节点最后一个块的高度",
          "type": "integer",
          "format": "uint64",
          "x-go-name": "LastBlockNumHeight"
        },
        "last_block_time": {
          "description": "采集时节点最后一个块的时间",
          "type": "string",
          "x-go-name": "LastBlockTime"
        },
        "last_block_transactions": {
          "description": "采集时节点最后一个块的交易数",
          "type": "integer",
          "format": "int64",
          "x-go-name": "LastBlockTransactions"
        },
        "node_id": {
          "description": "节点id",
          "type": "string",
          "x-go-name": "NodeID"
        },
        "node_ip": {
          "description": "节点ip",
          "type": "string",
          "x-go-name": "NodeIP"
        },
        "node_name": {
          "description": "节点名",
          "type": "string",
          "x-go-name": "NodeName"
        },
        "node_type": {
          "description": "节点类型",
          "type": "integer",
          "format": "int64",
          "x-go-name": "NodeType"
        },
        "os": {
          "description": "采集时节点的OS信息",
          "type": "string",
          "x-go-name": "OS"
        },
        "p2p_port": {
          "description": "节点 p2p监听端口",
          "type": "string",
          "x-go-name": "P2PPort"
        },
        "pbft_current_peer_list": {
          "description": "连接的当前轮pbft节点",
          "type": "array",
          "items": {
            "type": "string"
          },
          "x-go-name": "PbftCurrentPeerList"
        },
        "pbft_next_peer_list": {
          "description": "连接的下轮pbft 节点",
          "type": "array",
          "items": {
            "type": "string"
          },
          "x-go-name": "PbftNextPeerList"
        },
        "peers": {
          "description": "当前连接的p2p节点数",
          "type": "integer",
          "format": "int64",
          "x-go-name": "Peers"
        },
        "pending_transactions": {
          "description": "pending 的交易数",
          "type": "integer",
          "format": "int64",
          "x-go-name": "PendingTransactions"
        },
        "pre_ten_block": {
          "description": "采集时前10个块",
          "type": "array",
          "items": {
            "$ref": "#/definitions/BlockInfo"
          },
          "x-go-name": "PreTenBlock"
        },
        "queued_transactions": {
          "description": "queued 的交易数",
          "type": "integer",
          "format": "int64",
          "x-go-name": "QueuedTransactions"
        }
      },
      "x-go-package": "chainstack-monitor/monitor/model"
    },
    "RiskRecord": {
      "description": "风险记录",
      "type": "object",
      "properties": {
        "chain_id": {
          "description": "链id",
          "type": "string",
          "x-go-name": "ChainID"
        },
        "chain_version": {
          "description": "链版本",
          "type": "string",
          "x-go-name": "ChainVersion"
        },
        "current_block_hash": {
          "description": "上报时当前块hash",
          "type": "string",
          "x-go-name": "CurrentBlockHash"
        },
        "current_block_height": {
          "description": "上报时当前块高度",
          "type": "integer",
          "format": "uint64",
          "x-go-name": "CurrentBlockHeight"
        },
        "id": {
          "description": "全局唯一id",
          "type": "string",
          "x-go-name": "ID"
        },
        "node_id": {
          "description": "节点id",
          "type": "string",
          "x-go-name": "NodeID"
        },
        "node_ip": {
          "description": "节点ip",
          "type": "string",
          "x-go-name": "NodeIP"
        },
        "record_time": {
          "description": "记录时间",
          "type": "string",
          "format": "date-time",
          "x-go-name": "RecordTime"
        },
        "risk_info": {
          "description": "风险内容",
          "type": "object",
          "x-go-name": "RiskInfo"
        },
        "risk_type": {
          "description": "风险类型",
          "type": "integer",
          "format": "int64",
          "x-go-name": "RiskType"
        }
      },
      "x-go-package": "chainstack-monitor/monitor/model"
    }
  },
  "responses": {
    "baseResp": {
      "headers": {
        "info": {
          "type": "string"
        },
        "success": {
          "type": "boolean"
        }
      }
    },
    "getNodeRiskRecordResp": {
      "schema": {
        "type": "array",
        "items": {
          "$ref": "#/definitions/RiskRecord"
        }
      },
      "headers": {
        "info": {
          "type": "string"
        },
        "success": {
          "type": "boolean"
        }
      }
    },
    "getNodesResp": {
      "schema": {
        "type": "array",
        "items": {
          "$ref": "#/definitions/NodeCollectData"
        }
      },
      "headers": {
        "info": {
          "type": "string"
        },
        "success": {
          "type": "boolean"
        }
      }
    }
  }
}
```

**Comment by wedooo** [comment]
怎么解决的？

**Comment by Xib1uvXi** [comment]
> 怎么解决的？

json里加入这个： 

```json
"consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ]
```
