### ISSUE TITLE
Errors generating against 1.2 Swagger spec

### ISSUE THREAD

**Issue by rdiehl** [Swagger2Markup/swagger2markup#36]
We are still using Swagger 1.2 because of a regression in Swagger-UI that prevents us from upgrading at this time.  I found that the example outlined here https://swagger2markup.readme.io/docs/demo would not work with a 1.2 Swagger definition.  So based on the example Gradle script and JUnit test, I created a version that uses SwaggerCompatConverter to parse my file and send the resulting Swagger object to Swagger2MarkupConverter:

```
Swagger swagger = new SwaggerCompatConverter().read(temp.getAbsolutePath());
Swagger2MarkupConverter
    .from(swagger) 
    .build()
    .intoFolder("src/docs/asciidoc/generated");
```

When I create the Swagger object, I get a bunch of exceptions logged to standard error, but the JVM does not exit.  I reviewed the console output, and I appear to get 1 exception for each endpoint.  Here's one example, they all look basically the same:
```
java.io.FileNotFoundException: /var/folders/g6/plnk0r894t7gd5ch4dkjlttm0000gn/T/repository (No such file or directory)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at com.fasterxml.jackson.core.JsonFactory.createParser(JsonFactory.java:708)
	at com.fasterxml.jackson.databind.ObjectMapper.readTree(ObjectMapper.java:1846)
	at io.swagger.parser.SwaggerCompatConverter.readDeclaration(SwaggerCompatConverter.java:424)
	at io.swagger.parser.SwaggerCompatConverter.read(SwaggerCompatConverter.java:125)
	at io.swagger.parser.SwaggerCompatConverter.read(SwaggerCompatConverter.java:72)
	at com.docfinity.swagger.SwaggerDocGeneratorTests.convertRemoteSwaggerToAsciiDoc(SwaggerDocGeneratorTests.java:96)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)
```

The Swagger2MarkupConverter does complete, but the generated adoc/PDFs are mostly empty and just contain boilerplate stuff like table of contents;  none of my API is included.

Here is a gist of my 1.2 swagger definition:  https://gist.github.com/rdiehl/3d2405bbcf08006aecb1

Is this something I need to pass along to the swagger-parser project?

**Comment by RobWin** [comment]
Hi, thx. Could you please open an issue against [swagger-api/swagger-parser](https://github.com/swagger-api/swagger-parser). Its the official parser of Swagger which is used by this project. The issue seems to be a parser issue.
