### ISSUE TITLE
Error generating against 2.0 spec

### ISSUE THREAD

**Issue by rdiehl** [Swagger2Markup/swagger2markup#37]
Using a Swagger 2.0 compatible spec, I'm getting an error when trying to build the docs.  Here is my code:

```
Swagger2MarkupConverter
    .from(temp.getAbsolutePath()) 
    .build()
    .intoFolder("src/docs/asciidoc/generated");
```

This is the error that is generated:
```
java.lang.IllegalArgumentException: Multiple entries with same key: id=io.swagger.models.properties.StringProperty@1b4d89f and id=io.swagger.models.properties.StringProperty@1b4d89f
	at com.google.common.collect.ImmutableMap.checkNoConflict(ImmutableMap.java:150)
	at com.google.common.collect.RegularImmutableMap.checkNoConflictInBucket(RegularImmutableMap.java:104)
	at com.google.common.collect.RegularImmutableMap.<init>(RegularImmutableMap.java:70)
	at com.google.common.collect.ImmutableMap$Builder.build(ImmutableMap.java:254)
	at io.github.robwin.swagger2markup.builder.document.DefinitionsDocument.getAllProperties(DefinitionsDocument.java:210)
	at io.github.robwin.swagger2markup.builder.document.DefinitionsDocument.getAllProperties(DefinitionsDocument.java:195)
	at io.github.robwin.swagger2markup.builder.document.DefinitionsDocument.getAllProperties(DefinitionsDocument.java:204)
	at io.github.robwin.swagger2markup.builder.document.DefinitionsDocument.propertiesSection(DefinitionsDocument.java:172)
	at io.github.robwin.swagger2markup.builder.document.DefinitionsDocument.definition(DefinitionsDocument.java:168)
	at io.github.robwin.swagger2markup.builder.document.DefinitionsDocument.definitions(DefinitionsDocument.java:124)
	at io.github.robwin.swagger2markup.builder.document.DefinitionsDocument.build(DefinitionsDocument.java:107)
	at io.github.robwin.swagger2markup.Swagger2MarkupConverter.buildDocuments(Swagger2MarkupConverter.java:150)
	at io.github.robwin.swagger2markup.Swagger2MarkupConverter.intoFolder(Swagger2MarkupConverter.java:128)
	at com.docfinity.swagger.SwaggerDocGeneratorTests.convertRemoteSwaggerToAsciiDoc(SwaggerDocGeneratorTests.java:99)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)
```

This is a gist of the 2.0 version of my swagger.json: https://gist.github.com/rdiehl/55630bd808c743237417

**Comment by RobWin** [comment]
Wow. The Swagger file is huge. Could you please run it and change your logger to debug. We can see which definition model fails then.
Do you use composition/inheritance and `allOf`? It seems that its a inheritance issue that two models have the same property. Property overloading does not seem to work.

**Comment by RobWin** [comment]
The `$ref` seem to be wrong. They should not contain a description, but a model name.

**Comment by RobWin** [comment]
If you use and like Swagger2markup, I would love to get your GitHub Star.

**Comment by rdiehl** [comment]
Yes, we are using inheritance in a number of model objects.  I think this is an issue with the migration from Swagger spec 1.2 to 2.0.  Here's a blurb from our 1.2 Spec, that is able to be parsed:

```
"DashboardPromptDTO": {
"id": "DashboardPromptDTO",
"description": "",
"required": [
"name"
],
"extends": "com.docfinity.dashboards.dto.DashboardInputDTO",
"discriminator": "_class",
"properties": {
"label": {
"type": "string",
"description": "The prompt label."
},
"promptType": {
"$ref": "DashboardPromptType",
"description": "The prompt type.",
"enum": [
"SWITCH",
"DATE",
"DROP_DOWN_LIST",
"TEXT"
]
},
"name": {
"type": "string",
"description": "The input name, must be unique per dashboard."
},
"value": {
"$ref": "Object"
},
"id": {
"type": "string",
"description": "The ID of the DashboardInput."
},
"type": {
"$ref": "DashboardInputType",
"description": "The type of input.",
"enum": [
"DATASOURCE",
"STATIC",
"MACRO",
"DASHBOARD_PROMPT"
]
},
"ordinal": {
"type": "integer",
"format": "int32",
"description": "The ordinal."
},
"dataType": {
"$ref": "DataType",
"description": "The data type.",
"enum": [
"STRING",
"DATE",
"DECIMAL",
"INTEGER",
"BOOLEAN",
"STRING_ARRAY",
"DATE_ARRAY",
"DECIMAL_ARRAY",
"INTEGER_ARRAY",
"BOOLEAN_ARRAY"
]
},
"markedForDelete": {
"type": "boolean",
"description": "Whether this item should be deleted."
},
"datasourceId": {
"type": "string",
"description": "The ID of the datasource used by this input."
},
"datasourceName": {
"type": "string",
"description": "The name of the datasource used by this input."
},
"dashboardId": {
"type": "string",
"description": "The ID of the dashboard that owns this input."
},
"parameterClass": {
"$ref": "java.lang.Class<? extends com.docfinity.dashboards.entity.DashboardInput>"
},
"parameterPromptDto": {
"$ref": "ParameterPromptDTO"
},
"dashboardInputDatasourceInputs": {
"type": "array",
"description": "The inputs needed for the datasource for this input.",
"items": {
"$ref": "DashboardInputDatasourceInputDTO"
}
},
"macroValue": {
"type": "string"
},
"datasourceResults": {
"type": "array",
"description": "The results from executing the datasource.",
"items": {
"$ref": "DataValue"
}
},
"dashboardName": {
"type": "string",
"description": "The name of the dashboard that owns this input."
},
"responsibilityMapping": {
"type": "array",
"description": "The responsibility mapping for executing dependent inputs.",
"items": {
"type": "string"
}
}
},
"subTypes": [
"SwitchDashboardPromptDTO",
"DatasourceRequiredDashboardPromptDTO"
]
}
```

Here's the same blurb (I think) after we upgrade to Swagger 2.0:

```
"A user prompt input.": {
"allOf": [
{
"$ref": "#/definitions/An input to a dashboard."
},
{
"type": "object",
"required": [
"name"
],
"properties": {
"id": {
"type": "string",
"description": "The ID of the DashboardInput."
},
"name": {
"type": "string",
"description": "The input name, must be unique per dashboard."
},
"value": {
"type": "object"
},
"type": {
"type": "string",
"description": "The type of input.",
"enum": [
"DATASOURCE",
"STATIC",
"MACRO",
"DASHBOARD_PROMPT"
]
},
"dashboardId": {
"type": "string",
"description": "The ID of the dashboard that owns this input."
},
"dashboardName": {
"type": "string",
"description": "The name of the dashboard that owns this input."
},
"dataType": {
"type": "string",
"description": "The data type.",
"enum": [
"STRING",
"DATE",
"DECIMAL",
"INTEGER",
"BOOLEAN",
"STRING_ARRAY",
"DATE_ARRAY",
"DECIMAL_ARRAY",
"INTEGER_ARRAY",
"BOOLEAN_ARRAY"
]
},
"ordinal": {
"type": "integer",
"format": "int32",
"description": "The ordinal."
},
"datasourceId": {
"type": "string",
"description": "The ID of the datasource used by this input."
},
"datasourceName": {
"type": "string",
"description": "The name of the datasource used by this input."
},
"datasourceResults": {
"type": "array",
"description": "The results from executing the datasource.",
"items": {
"$ref": "#/definitions/Data value used to represent a generic key value pair."
}
},
"markedForDelete": {
"type": "boolean",
"description": "Whether this item should be deleted.",
"default": false
},
"responsibilityMapping": {
"type": "array",
"description": "The responsibility mapping for executing dependent inputs.",
"items": {
"type": "string"
}
},
"dashboardInputDatasourceInputs": {
"type": "array",
"description": "The inputs needed for the datasource for this input.",
"items": {
"$ref": "#/definitions/DashboardInputDatasourceInputDTO"
}
},
"label": {
"type": "string",
"description": "The prompt label."
},
"promptType": {
"type": "string",
"description": "The prompt type.",
"enum": [
"SWITCH",
"DATE",
"TEXT",
"DROP_DOWN_LIST"
]
},
"macroValue": {
"type": "string"
},
"parameterPromptDto": {
"$ref": "#/definitions/A generic representation of a user prompt."
}
}
}
]
}
```

We are using swagger-annotations to generate the swagger spec dynamically at runtime.  So based on your experience, is this something that would need to be logged against the swagger-core or another swagger project?  It certainly seems like a regression in behavior somewhere.

**Comment by RobWin** [comment]
Which tool do you use to generate the Swagger JSON from source code?
Swagger-maven-plugin or Springfox or something else?

Which tool did you use to migrate from v1.2 to v2.0?

**Comment by rdiehl** [comment]
We're using the Swagger JAX-RS stuff to generate: https://github.com/swagger-api/swagger-core/wiki/Swagger-Core-JAX-RS-Project-Setup-1.5.X

The migration was just upgrading JAR files and tweaking a few things.  So I'm guessing I need to report this under swagger-core?

**Comment by RobWin** [comment]
Yes, Swagger-core is correct.
